# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_OPTEE2) += optee2.o
optee2-objs += core.o
optee2-objs += call.o
optee2-objs += rpc.o
optee2-objs += supp.o
optee2-objs += shm_pool.o
optee2-objs += device.o
